In [1]:
#https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

In [7]:
import torch

In [8]:
x = torch.ones(2, 2, requires_grad=True)

In [9]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [10]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [11]:
print(y.grad_fn)

In [12]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [13]:
a = torch.randn(2, 2)

In [14]:
a

tensor([[ 1.5068,  1.4824],
        [-0.3315,  0.4680]])

In [15]:
a = ((a*3)/(a-1))

In [16]:
a

tensor([[ 8.9191,  9.2190],
        [ 0.7469, -2.6394]])

In [17]:
print(a.requires_grad)

False


In [18]:
a.requires_grad_(True)

tensor([[ 8.9191,  9.2190],
        [ 0.7469, -2.6394]], requires_grad=True)

In [19]:
b = (a*a).sum()

In [20]:
b

tensor(172.0646, grad_fn=<SumBackward0>)

In [21]:
out.backward()

In [22]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [23]:
x = torch.randn(3, requires_grad=True)

In [24]:
x

tensor([-0.0227, -0.9757, -0.6001], requires_grad=True)

In [25]:
y = x * 2

In [26]:
y

tensor([-0.0454, -1.9513, -1.2001], grad_fn=<MulBackward>)

In [27]:
while y.data.norm() < 1000:
    y = y * 2

In [28]:
print(y)

tensor([ -23.2373, -999.0671, -614.4612], grad_fn=<MulBackward>)


In [29]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)

In [31]:
y.backward(gradients)

In [32]:
print(x.grad)

tensor([ 102.4000, 1024.0000,    0.1024])


In [33]:
print(x.requires_grad)

True


In [34]:
print((x**2).requires_grad)

True


In [35]:
with torch.no_grad():
    print((x**2).requires_grad)

False
