In [1]:
#https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#

In [2]:
from __future__ import print_function
import torch

In [8]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 1.0842e-19, 0.0000e+00],
        [1.0842e-19, 5.6052e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.0842e-19, 3.6408e+37]])


In [12]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8758, 0.1254, 0.5224],
        [0.2650, 0.0407, 0.6607],
        [0.9388, 0.8120, 0.1997],
        [0.0729, 0.7587, 0.3013],
        [0.1851, 0.2313, 0.0770]])


In [13]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [14]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [18]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [19]:
x = torch.randn_like(x, dtype=torch.float)
print(x)  

tensor([[-0.6470,  0.0648, -0.0067],
        [ 0.8523, -1.0006,  1.5021],
        [ 0.5181, -0.0492, -0.6628],
        [-0.3969,  0.5903,  0.5261],
        [ 0.4096, -0.8883,  1.6652]])


In [20]:
print(x.size())

torch.Size([5, 3])


In [22]:
x

tensor([[-0.6470,  0.0648, -0.0067],
        [ 0.8523, -1.0006,  1.5021],
        [ 0.5181, -0.0492, -0.6628],
        [-0.3969,  0.5903,  0.5261],
        [ 0.4096, -0.8883,  1.6652]])

In [23]:
y

tensor([[0.5725, 0.1776, 0.7886],
        [0.8993, 0.3629, 0.1875],
        [0.4545, 0.2747, 0.9812],
        [0.0809, 0.6632, 0.1551],
        [0.5372, 0.8543, 0.9666]])

In [21]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.0744,  0.2424,  0.7819],
        [ 1.7516, -0.6377,  1.6895],
        [ 0.9726,  0.2256,  0.3184],
        [-0.3159,  1.2535,  0.6812],
        [ 0.9468, -0.0340,  2.6318]])


In [24]:
print(torch.add(x, y))

tensor([[-0.0744,  0.2424,  0.7819],
        [ 1.7516, -0.6377,  1.6895],
        [ 0.9726,  0.2256,  0.3184],
        [-0.3159,  1.2535,  0.6812],
        [ 0.9468, -0.0340,  2.6318]])


In [25]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.0744,  0.2424,  0.7819],
        [ 1.7516, -0.6377,  1.6895],
        [ 0.9726,  0.2256,  0.3184],
        [-0.3159,  1.2535,  0.6812],
        [ 0.9468, -0.0340,  2.6318]])


In [37]:
y.add_(x)
print(y)

tensor([[-3.3092,  0.5663,  0.7485],
        [ 6.0129, -5.6405,  9.1998],
        [ 3.5629, -0.0204, -2.9955],
        [-2.3004,  4.2051,  3.3116],
        [ 2.9946, -4.4756, 10.9580]])


In [38]:
print(x[:, 1])

tensor([ 0.0648, -1.0006, -0.0492,  0.5903, -0.8883])


In [39]:
x = torch.randn(4, 4)

In [40]:
x

tensor([[ 0.5436, -0.8024, -0.9595,  0.3738],
        [-0.5932,  0.0645,  1.8282,  0.5706],
        [ 1.3912,  0.4216, -0.2699, -0.5678],
        [-1.7967, -1.2430,  0.7470, -0.3632]])

In [41]:
y = x.view(16)

In [42]:
y

tensor([ 0.5436, -0.8024, -0.9595,  0.3738, -0.5932,  0.0645,  1.8282,  0.5706,
         1.3912,  0.4216, -0.2699, -0.5678, -1.7967, -1.2430,  0.7470, -0.3632])

In [43]:
z = x.view(-1, 8)

In [44]:
z

tensor([[ 0.5436, -0.8024, -0.9595,  0.3738, -0.5932,  0.0645,  1.8282,  0.5706],
        [ 1.3912,  0.4216, -0.2699, -0.5678, -1.7967, -1.2430,  0.7470, -0.3632]])

In [45]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [46]:
x = torch.randn(1)

In [47]:
print(x)

tensor([1.1585])


In [48]:
x.item()

1.158531665802002

In [49]:
a = torch.ones(5)

In [50]:
a

tensor([1., 1., 1., 1., 1.])

In [51]:
b = a.numpy()

In [52]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [53]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [54]:
print(a)

tensor([2., 2., 2., 2., 2.])


In [55]:
print(b)

[2. 2. 2. 2. 2.]


In [56]:
import numpy as np

In [64]:
a = np.ones(5)

In [65]:
a

array([1., 1., 1., 1., 1.])

In [66]:
b = torch.from_numpy(a)

In [67]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [68]:
np.add(a, 1, out=a)

array([2., 2., 2., 2., 2.])

In [69]:
a

array([2., 2., 2., 2., 2.])

In [70]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [72]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))